export const SERVICE_SECTORS = [
  'Home Services',
  'Healthcare',
  'Education',
  'Food & Dining',
  'Automotive',
  'Beauty & Wellness',
  'Construction & Interiors',
  'Retail Shops',
  'Professional Services',
  'Hotels & Travel',
  'Religious & Community',
  'Agriculture & Farming',
  'Textiles & Fashion',
  'Manufacturing & Industry',
  'Entertainment & Events',
] as const;

export type ServiceSector = typeof SERVICE_SECTORS[number];

export interface ServiceTagSeed {
  name: string;
  nameMl: string;
  sector: ServiceSector;
}

export const SERVICE_TAGS_SEED: ServiceTagSeed[] = [
  // Home Services
  { name: 'Electrician', nameMl: 'ഇലക്ട്രീഷ്യൻ', sector: 'Home Services' },
  { name: 'Plumber', nameMl: 'പ്ലംബർ', sector: 'Home Services' },
  { name: 'Carpenter', nameMl: 'ആശാരി', sector: 'Home Services' },
  { name: 'Painter', nameMl: 'പെയിന്റർ', sector: 'Home Services' },
  { name: 'Welder', nameMl: 'വെൽഡർ', sector: 'Home Services' },
  { name: 'Mason', nameMl: 'കല്ലാശാരി', sector: 'Home Services' },
  { name: 'AC Repair', nameMl: 'AC റിപ്പയർ', sector: 'Home Services' },
  { name: 'AC Installation', nameMl: 'AC ഇൻസ്റ്റലേഷൻ', sector: 'Home Services' },
  { name: 'Refrigerator Repair', nameMl: 'ഫ്രിഡ്ജ് റിപ്പയർ', sector: 'Home Services' },
  { name: 'Washing Machine Repair', nameMl: 'വാഷിംഗ് മെഷീൻ റിപ്പയർ', sector: 'Home Services' },
  { name: 'TV Repair', nameMl: 'ടിവി റിപ്പയർ', sector: 'Home Services' },
  { name: 'Inverter & Battery Service', nameMl: 'ഇൻവെർട്ടർ സർവ്വീസ്', sector: 'Home Services' },
  { name: 'Solar Panel Installation', nameMl: 'സോളാർ ഇൻസ്റ്റലേഷൻ', sector: 'Home Services' },
  { name: 'CCTV Installation', nameMl: 'CCTV ഇൻസ്റ്റലേഷൻ', sector: 'Home Services' },
  { name: 'Water Tank Cleaning', nameMl: 'വാട്ടർ ടാങ്ക് ക്ലീനിംഗ്', sector: 'Home Services' },
  { name: 'Pest Control', nameMl: 'കീടനിയന്ത്രണം', sector: 'Home Services' },
  { name: 'Sofa & Upholstery Cleaning', nameMl: 'സോഫ ക്ലീനിംഗ്', sector: 'Home Services' },
  { name: 'Carpet Cleaning', nameMl: 'കാർപ്പറ്റ് ക്ലീനിംഗ്', sector: 'Home Services' },
  { name: 'Home Cleaning', nameMl: 'ഹോം ക്ലീനിംഗ്', sector: 'Home Services' },
  { name: 'Packers & Movers', nameMl: 'പ്യാക്കേഴ്‌സ് & മൂവേഴ്‌സ്', sector: 'Home Services' },
  { name: 'Plumbing Work', nameMl: 'പ്ലംബിംഗ്', sector: 'Home Services' },
  { name: 'Waterproofing', nameMl: 'വാട്ടർപ്രൂഫിംഗ്', sector: 'Home Services' },
  { name: 'CCTV & Security Systems', nameMl: 'സുരക്ഷാ സംവിധാനം', sector: 'Home Services' },
  { name: 'Bore Well Drilling', nameMl: 'ബോർ വെൽ', sector: 'Home Services' },
  { name: 'Well Construction & Cleaning', nameMl: 'കിണർ നിർമ്മാണം', sector: 'Home Services' },
  { name: 'Driver (On Call)', nameMl: 'ഡ്രൈവർ', sector: 'Home Services' },
  { name: 'Caretaker / Babysitter', nameMl: 'കെയർടേക്കർ', sector: 'Home Services' },
  { name: 'Cook (Home)', nameMl: 'പാചകക്കാർ', sector: 'Home Services' },
  { name: 'Laundry & Ironing', nameMl: 'ലോൺഡ്രി', sector: 'Home Services' },
  { name: 'Gas Stove Repair', nameMl: 'ഗ്യാസ് സ്റ്റൗ റിപ്പയർ', sector: 'Home Services' },

  // Healthcare
  { name: 'General Physician', nameMl: 'ജനറൽ ഡോക്ടർ', sector: 'Healthcare' },
  { name: 'Dentist', nameMl: 'ദന്ത ഡോക്ടർ', sector: 'Healthcare' },
  { name: 'Pediatrician', nameMl: 'ശിശുരോഗ വിദഗ്ദ്ധൻ', sector: 'Healthcare' },
  { name: 'Gynecologist', nameMl: 'ഗൈനക്കോളജിസ്റ്റ്', sector: 'Healthcare' },
  { name: 'Orthopedic Surgeon', nameMl: 'ഓർത്തോപീഡിക്', sector: 'Healthcare' },
  { name: 'Dermatologist', nameMl: 'ചർമ്മ ഡോക്ടർ', sector: 'Healthcare' },
  { name: 'Cardiologist', nameMl: 'ഹൃദ്രോഗ വിദഗ്ദ്ധൻ', sector: 'Healthcare' },
  { name: 'Neurologist', nameMl: 'ന്യൂറോളജിസ്റ്റ്', sector: 'Healthcare' },
  { name: 'Eye Specialist (Ophthalmologist)', nameMl: 'നേത്രരോഗ ഡോക്ടർ', sector: 'Healthcare' },
  { name: 'ENT Specialist', nameMl: 'ENT ഡോക്ടർ', sector: 'Healthcare' },
  { name: 'Ayurveda Doctor', nameMl: 'ആയുർവേദ ഡോക്ടർ', sector: 'Healthcare' },
  { name: 'Ayurveda Panchakarma', nameMl: 'പഞ്ചകർമ', sector: 'Healthcare' },
  { name: 'Homeopathy Doctor', nameMl: 'ഹോമിയോ ഡോക്ടർ', sector: 'Healthcare' },
  { name: 'Physiotherapy', nameMl: 'ഫിസിയോതെറാപ്പി', sector: 'Healthcare' },
  { name: 'Diagnostic Lab', nameMl: 'ഡയഗ്നോസ്റ്റിക് ലാബ്', sector: 'Healthcare' },
  { name: 'X-Ray & Scanning Centre', nameMl: 'സ്‌കാനിംഗ് സെന്റർ', sector: 'Healthcare' },
  { name: 'Pharmacy', nameMl: 'മെഡിക്കൽ സ്റ്റോർ', sector: 'Healthcare' },
  { name: 'Veterinary Doctor', nameMl: 'വെറ്ററിനറി ഡോക്ടർ', sector: 'Healthcare' },
  { name: 'Nursing Home / Clinic', nameMl: 'ക്ലിനിക്', sector: 'Healthcare' },
  { name: 'Multi-Specialty Hospital', nameMl: 'ആശുപത്രി', sector: 'Healthcare' },
  { name: 'Blood Bank', nameMl: 'ബ്ലഡ് ബാങ്ക്', sector: 'Healthcare' },
  { name: 'Ambulance Service', nameMl: 'ആംബുലൻസ്', sector: 'Healthcare' },
  { name: 'Yoga & Meditation Centre', nameMl: 'യോഗ കേന്ദ്രം', sector: 'Healthcare' },
  { name: 'Naturopathy', nameMl: 'നേച്ചർ ക്യൂർ', sector: 'Healthcare' },
  { name: 'Psychiatrist', nameMl: 'മനോരോഗ ഡോക്ടർ', sector: 'Healthcare' },
  { name: 'Dietitian & Nutritionist', nameMl: 'ഡയറ്റീഷ്യൻ', sector: 'Healthcare' },

  // Education
  { name: 'School', nameMl: 'സ്‌കൂൾ', sector: 'Education' },
  { name: 'College', nameMl: 'കോളേജ്', sector: 'Education' },
  { name: 'Engineering College', nameMl: 'എഞ്ചിനീയറിംഗ് കോളേജ്', sector: 'Education' },
  { name: 'Medical College', nameMl: 'മെഡിക്കൽ കോളേജ്', sector: 'Education' },
  { name: 'Nursing College', nameMl: 'നഴ്‌സിംഗ് കോളേജ്', sector: 'Education' },
  { name: 'Coaching Centre', nameMl: 'കോച്ചിംഗ് സെന്റർ', sector: 'Education' },
  { name: 'NEET Coaching', nameMl: 'NEET കോച്ചിംഗ്', sector: 'Education' },
  { name: 'JEE Coaching', nameMl: 'JEE കോച്ചിംഗ്', sector: 'Education' },
  { name: 'PSC Coaching', nameMl: 'PSC കോച്ചിംഗ്', sector: 'Education' },
  { name: 'IELTS & English Coaching', nameMl: 'IELTS കോച്ചിംഗ്', sector: 'Education' },
  { name: 'Computer Classes', nameMl: 'കമ്പ്യൂട്ടർ ക്ലാസ്', sector: 'Education' },
  { name: 'Driving School', nameMl: 'ഡ്രൈവിംഗ് സ്‌കൂൾ', sector: 'Education' },
  { name: 'Music Classes', nameMl: 'സംഗീത ക്ലാസ്', sector: 'Education' },
  { name: 'Dance Classes', nameMl: 'ഡാൻസ് ക്ലാസ്', sector: 'Education' },
  { name: 'Yoga Classes', nameMl: 'യോഗ ക്ലാസ്', sector: 'Education' },
  { name: 'Tailoring & Fashion Design Classes', nameMl: 'തയ്യൽ ക്ലാസ്', sector: 'Education' },
  { name: 'Art & Painting Classes', nameMl: 'ചിത്രരചന ക്ലാസ്', sector: 'Education' },
  { name: 'Tuition Centre', nameMl: 'ട്യൂഷൻ സെന്റർ', sector: 'Education' },
  { name: 'Spoken English Classes', nameMl: 'ഇംഗ്ലീഷ് ക്ലാസ്', sector: 'Education' },
  { name: 'Montessori / Play School', nameMl: 'പ്ലേ സ്‌കൂൾ', sector: 'Education' },
  { name: 'Martial Arts', nameMl: 'കളരി / മാർഷ്യൽ ആർട്ട്', sector: 'Education' },
  { name: 'Swimming Classes', nameMl: 'നീന്തൽ ക്ലാസ്', sector: 'Education' },

  // Food & Dining
  { name: 'Restaurant', nameMl: 'റെസ്റ്റോറന്റ്', sector: 'Food & Dining' },
  { name: 'Hotel (Meals)', nameMl: 'ഹോട്ടൽ', sector: 'Food & Dining' },
  { name: 'Fast Food', nameMl: 'ഫാസ്റ്റ് ഫുഡ്', sector: 'Food & Dining' },
  { name: 'Kerala Meals', nameMl: 'കേരള ഊണ്', sector: 'Food & Dining' },
  { name: 'Biryani', nameMl: 'ബിരിയാണി', sector: 'Food & Dining' },
  { name: 'Bakery', nameMl: 'ബേക്കറി', sector: 'Food & Dining' },
  { name: 'Juice Shop', nameMl: 'ജ്യൂസ് ഷോപ്പ്', sector: 'Food & Dining' },
  { name: 'Ice Cream Parlour', nameMl: 'ഐസ്‌ക്രീം', sector: 'Food & Dining' },
  { name: 'Cake Shop', nameMl: 'കേക്ക് ഷോപ്പ്', sector: 'Food & Dining' },
  { name: 'Catering Service', nameMl: 'കേറ്ററിംഗ്', sector: 'Food & Dining' },
  { name: 'Tiffin & Home Food Delivery', nameMl: 'ടിഫിൻ സർവ്വീസ്', sector: 'Food & Dining' },
  { name: 'Cloud Kitchen', nameMl: 'ക്ലൗഡ് കിച്ചൻ', sector: 'Food & Dining' },
  { name: 'Fish Market', nameMl: 'മീൻ മാർക്കറ്റ്', sector: 'Food & Dining' },
  { name: 'Meat & Chicken Shop', nameMl: 'ഇറച്ചി കട', sector: 'Food & Dining' },
  { name: 'Tea Stall & Chai Shop', nameMl: 'ചായ കട', sector: 'Food & Dining' },
  { name: 'Vegetable & Fruit Shop', nameMl: 'പഴം-പച്ചക്കറി', sector: 'Food & Dining' },
  { name: 'Sweet Shop', nameMl: 'മിഠായി കട', sector: 'Food & Dining' },
  { name: 'Pickle & Home-Made Products', nameMl: 'അച്ചാർ & ഭക്ഷ്യ ഉൽപ്പന്നങ്ങൾ', sector: 'Food & Dining' },

  // Automotive
  { name: 'Car Service Centre', nameMl: 'കാർ സർവ്വീസ്', sector: 'Automotive' },
  { name: 'Bike & Scooter Service', nameMl: 'ബൈക്ക് സർവ്വീസ്', sector: 'Automotive' },
  { name: 'Tyre Shop', nameMl: 'ടയർ ഷോപ്പ്', sector: 'Automotive' },
  { name: 'Car Wash', nameMl: 'കാർ വാഷ്', sector: 'Automotive' },
  { name: 'Auto Spare Parts', nameMl: 'സ്‌പെയർ പാർട്‌സ്', sector: 'Automotive' },
  { name: 'Car AC Repair', nameMl: 'കാർ AC റിപ്പയർ', sector: 'Automotive' },
  { name: 'Car Denting & Painting', nameMl: 'ബോഡി ഷോപ്പ്', sector: 'Automotive' },
  { name: 'Electric Vehicle Service', nameMl: 'EV സർവ്വീസ്', sector: 'Automotive' },
  { name: 'Auto Rickshaw', nameMl: 'ഓട്ടോ', sector: 'Automotive' },
  { name: 'Car Rental', nameMl: 'കാർ ഭാടകം', sector: 'Automotive' },
  { name: 'Driving School', nameMl: 'ഡ്രൈവിംഗ് സ്‌കൂൾ', sector: 'Automotive' },
  { name: 'Vehicle Insurance', nameMl: 'വാഹന ഇൻഷുറൻസ്', sector: 'Automotive' },
  { name: 'RTO & Vehicle Services', nameMl: 'RTO സേവനം', sector: 'Automotive' },
  { name: 'Towing Service', nameMl: 'ടോയിംഗ്', sector: 'Automotive' },

  // Beauty & Wellness
  { name: 'Ladies Salon', nameMl: 'ലേഡീസ് സലൂൺ', sector: 'Beauty & Wellness' },
  { name: 'Gents Salon & Barber Shop', nameMl: 'ബാർബർ ഷോപ്പ്', sector: 'Beauty & Wellness' },
  { name: 'Bridal Makeup', nameMl: 'ബ്രൈഡൽ മേക്കപ്പ്', sector: 'Beauty & Wellness' },
  { name: 'Mehndi Artist', nameMl: 'മൈലാഞ്ചി', sector: 'Beauty & Wellness' },
  { name: 'Spa & Massage', nameMl: 'സ്പാ & മസ്സാജ്', sector: 'Beauty & Wellness' },
  { name: 'Gymnasium', nameMl: 'ജിം', sector: 'Beauty & Wellness' },
  { name: 'Yoga Studio', nameMl: 'യോഗ സ്റ്റുഡിയോ', sector: 'Beauty & Wellness' },
  { name: 'Fitness Trainer (Home Visit)', nameMl: 'ഫിറ്റ്‌നസ് ട്രെയിനർ', sector: 'Beauty & Wellness' },
  { name: 'Tattoo Studio', nameMl: 'ടാറ്റൂ', sector: 'Beauty & Wellness' },
  { name: 'Nail Studio', nameMl: 'നെയ്ൽ ആർട്ട്', sector: 'Beauty & Wellness' },
  { name: 'Ayurveda Beauty Treatment', nameMl: 'ആയുർവേദ സൗന്ദര്യ ചികിത്സ', sector: 'Beauty & Wellness' },
  { name: 'Skin Care Clinic', nameMl: 'സ്‌കിൻ കെയർ', sector: 'Beauty & Wellness' },
  { name: 'Slimming Centre', nameMl: 'സ്ലിമ്മിംഗ് സെന്റർ', sector: 'Beauty & Wellness' },

  // Construction & Interiors
  { name: 'Civil Contractor', nameMl: 'കോൺട്രാക്ടർ', sector: 'Construction & Interiors' },
  { name: 'Architect', nameMl: 'ആർക്കിടെക്ട്', sector: 'Construction & Interiors' },
  { name: 'Interior Designer', nameMl: 'ഇന്റീരിയർ ഡിസൈനർ', sector: 'Construction & Interiors' },
  { name: 'Tiles & Flooring', nameMl: 'ടൈൽസ്', sector: 'Construction & Interiors' },
  { name: 'Plywood & Hardware', nameMl: 'പ്ലൈവുഡ് & ഹാർഡ്‌വെയർ', sector: 'Construction & Interiors' },
  { name: 'Paint & Varnish Dealer', nameMl: 'പെയിന്റ് ഡീലർ', sector: 'Construction & Interiors' },
  { name: 'Aluminium & Glass Works', nameMl: 'അലൂമിനിയം & ഗ്ലാസ്', sector: 'Construction & Interiors' },
  { name: 'Granite & Marble', nameMl: 'ഗ്രാനൈറ്റ്', sector: 'Construction & Interiors' },
  { name: 'Furniture Maker', nameMl: 'ഫർണിച്ചർ', sector: 'Construction & Interiors' },
  { name: 'Modular Kitchen', nameMl: 'മോഡുലാർ കിച്ചൻ', sector: 'Construction & Interiors' },
  { name: 'False Ceiling', nameMl: 'ഫാൾസ് സീലിംഗ്', sector: 'Construction & Interiors' },
  { name: 'PVC & UPVC Windows & Doors', nameMl: 'PVC വാതിലുകൾ', sector: 'Construction & Interiors' },
  { name: 'Concrete & Ready Mix', nameMl: 'കോൺക്രീറ്റ്', sector: 'Construction & Interiors' },
  { name: 'Soil Testing', nameMl: 'മണ്ണ് പരിശോധന', sector: 'Construction & Interiors' },
  { name: 'Structural Engineer', nameMl: 'സ്ട്രക്ചറൽ എഞ്ചിനീയർ', sector: 'Construction & Interiors' },
  { name: 'Electrical Contractor', nameMl: 'ഇലക്ട്രിക്കൽ കോൺട്രാക്ടർ', sector: 'Construction & Interiors' },

  // Retail Shops
  { name: 'Grocery Store', nameMl: 'പലചരക്ക് കട', sector: 'Retail Shops' },
  { name: 'Supermarket', nameMl: 'സൂപ്പർമാർക്കറ്റ്', sector: 'Retail Shops' },
  { name: 'Electronics Shop', nameMl: 'ഇലക്ട്രോണിക്‌സ്', sector: 'Retail Shops' },
  { name: 'Mobile & Accessories Shop', nameMl: 'മൊബൈൽ ഷോപ്പ്', sector: 'Retail Shops' },
  { name: 'Jewellery Shop', nameMl: 'ആഭരണ കട', sector: 'Retail Shops' },
  { name: 'Optical Store', nameMl: 'കണ്ണട കട', sector: 'Retail Shops' },
  { name: 'Book Store & Stationery', nameMl: 'ബുക്ക് സ്‌റ്റോർ', sector: 'Retail Shops' },
  { name: 'Gift Shop', nameMl: 'ഗിഫ്റ്റ് ഷോപ്പ്', sector: 'Retail Shops' },
  { name: 'Toy Shop', nameMl: 'കളിപ്പാട്ടം', sector: 'Retail Shops' },
  { name: 'Sports Shop', nameMl: 'സ്‌പോർട്‌സ്', sector: 'Retail Shops' },
  { name: 'Bicycle Shop', nameMl: 'സൈക്കിൾ ഷോപ്പ്', sector: 'Retail Shops' },
  { name: 'Fertilizer & Seeds', nameMl: 'കൃഷി കട', sector: 'Retail Shops' },
  { name: 'Medical Equipment & Supplies', nameMl: 'മെഡിക്കൽ ഉപകരണം', sector: 'Retail Shops' },
  { name: 'Hardware Store', nameMl: 'ഹാർഡ്‌വെയർ', sector: 'Retail Shops' },
  { name: 'Pet Shop', nameMl: 'പെറ്റ് ഷോപ്പ്', sector: 'Retail Shops' },
  { name: 'Shoe Store', nameMl: 'ഷൂ ഷോപ്പ്', sector: 'Retail Shops' },
  { name: 'Bag & Luggage Store', nameMl: 'ബാഗ് ഷോപ്പ്', sector: 'Retail Shops' },
  { name: 'Kitchen & Cookware Shop', nameMl: 'പാത്ര കട', sector: 'Retail Shops' },

  // Professional Services
  { name: 'Lawyer / Advocate', nameMl: 'അഭിഭാഷകൻ', sector: 'Professional Services' },
  { name: 'CA / Accountant', nameMl: 'ചാർട്ടേഡ് അക്കൗണ്ടന്റ്', sector: 'Professional Services' },
  { name: 'Tax Consultant', nameMl: 'നികുതി ഉപദേഷ്ടാവ്', sector: 'Professional Services' },
  { name: 'Insurance Agent', nameMl: 'ഇൻഷുറൻസ്', sector: 'Professional Services' },
  { name: 'Real Estate Agent', nameMl: 'റിയൽ എസ്റ്റേറ്റ്', sector: 'Professional Services' },
  { name: 'Notary', nameMl: 'നോട്ടറി', sector: 'Professional Services' },
  { name: 'Photographer', nameMl: 'ഫോട്ടോഗ്രാഫർ', sector: 'Professional Services' },
  { name: 'Videographer', nameMl: 'വിഡിയോഗ്രാഫർ', sector: 'Professional Services' },
  { name: 'Graphic Designer', nameMl: 'ഗ്രാഫിക് ഡിസൈനർ', sector: 'Professional Services' },
  { name: 'Printing Press', nameMl: 'പ്രിന്റിംഗ്', sector: 'Professional Services' },
  { name: 'Courier Service', nameMl: 'കൊറിയർ', sector: 'Professional Services' },
  { name: 'Web Designer / Developer', nameMl: 'വെബ് ഡെവലപ്പർ', sector: 'Professional Services' },
  { name: 'Digital Marketing', nameMl: 'ഡിജിറ്റൽ മാർക്കറ്റിംഗ്', sector: 'Professional Services' },
  { name: 'Recruitment & HR Services', nameMl: 'റിക്രൂട്ട്‌മെന്റ്', sector: 'Professional Services' },
  { name: 'Security Guard Services', nameMl: 'സെക്യൂരിറ്റി', sector: 'Professional Services' },
  { name: 'Translation Services', nameMl: 'പരിഭാഷ', sector: 'Professional Services' },

  // Hotels & Travel
  { name: 'Hotel', nameMl: 'ഹോട്ടൽ', sector: 'Hotels & Travel' },
  { name: 'Resort', nameMl: 'റിസോർട്ട്', sector: 'Hotels & Travel' },
  { name: 'Homestay', nameMl: 'ഹോം സ്‌റ്റേ', sector: 'Hotels & Travel' },
  { name: 'Guest House', nameMl: 'ഗസ്‌റ്റ് ഹൗസ്', sector: 'Hotels & Travel' },
  { name: 'Service Apartment', nameMl: 'സർവ്വീസ് അപ്പാർട്ട്‌മെന്റ്', sector: 'Hotels & Travel' },
  { name: 'Houseboat', nameMl: 'ഹൗസ്ബോട്ട്', sector: 'Hotels & Travel' },
  { name: 'Ayurveda Resort', nameMl: 'ആയുർവേദ റിസോർട്ട്', sector: 'Hotels & Travel' },
  { name: 'Tour Operator', nameMl: 'ടൂർ ഓപ്പറേറ്റർ', sector: 'Hotels & Travel' },
  { name: 'Travel Agency', nameMl: 'ട്രാവൽ ഏജൻസി', sector: 'Hotels & Travel' },
  { name: 'Bus Booking', nameMl: 'ബസ് ബുക്കിംഗ്', sector: 'Hotels & Travel' },
  { name: 'Flight Booking', nameMl: 'ഫ്ലൈറ്റ് ബുക്കിംഗ്', sector: 'Hotels & Travel' },
  { name: 'Taxi & Cab Service', nameMl: 'ടാക്‌സി', sector: 'Hotels & Travel' },
  { name: 'Boat & Cruise Service', nameMl: 'ബോട്ട് ക്രൂയിസ്', sector: 'Hotels & Travel' },

  // Religious & Community
  { name: 'Temple', nameMl: 'ക്ഷേത്രം', sector: 'Religious & Community' },
  { name: 'Church', nameMl: 'പള്ളി', sector: 'Religious & Community' },
  { name: 'Mosque', nameMl: 'മസ്‌ജിദ്', sector: 'Religious & Community' },
  { name: 'Charitable Trust & NGO', nameMl: 'ചാരിറ്റബിൾ ട്രസ്റ്റ്', sector: 'Religious & Community' },
  { name: 'Community Hall / Auditorium', nameMl: 'കമ്മ്യൂണിറ്റി ഹാൾ', sector: 'Religious & Community' },
  { name: 'Funeral Services', nameMl: 'ശവസംസ്‌കാര സേവനം', sector: 'Religious & Community' },
  { name: 'Astrologer / Jyothisham', nameMl: 'ജ്യോതിഷം', sector: 'Religious & Community' },

  // Agriculture & Farming
  { name: 'Rubber Tapping & Trading', nameMl: 'റബ്ബർ', sector: 'Agriculture & Farming' },
  { name: 'Coconut Trading', nameMl: 'തേങ്ങ', sector: 'Agriculture & Farming' },
  { name: 'Paddy & Rice Mill', nameMl: 'നെൽ മില്ല്', sector: 'Agriculture & Farming' },
  { name: 'Spice Trading', nameMl: 'സുഗന്ധദ്രവ്യം', sector: 'Agriculture & Farming' },
  { name: 'Nursery & Plants', nameMl: 'നഴ്‌സറി', sector: 'Agriculture & Farming' },
  { name: 'Poultry Farm', nameMl: 'കോഴി ഫാം', sector: 'Agriculture & Farming' },
  { name: 'Dairy Farm', nameMl: 'ഡയറി', sector: 'Agriculture & Farming' },
  { name: 'Organic Farming', nameMl: 'ജൈവ കൃഷി', sector: 'Agriculture & Farming' },
  { name: 'Agricultural Equipment', nameMl: 'കൃഷി യന്ത്രം', sector: 'Agriculture & Farming' },
  { name: 'Fish Farming & Aquaculture', nameMl: 'മത്സ്യ ഫാം', sector: 'Agriculture & Farming' },

  // Textiles & Fashion
  { name: 'Clothing Store', nameMl: 'തുണിക്കട', sector: 'Textiles & Fashion' },
  { name: 'Saree & Silk Store', nameMl: 'സാരി', sector: 'Textiles & Fashion' },
  { name: 'Readymade Garments', nameMl: 'റെഡിമേഡ്', sector: 'Textiles & Fashion' },
  { name: 'Tailor', nameMl: 'തയ്യൽക്കാർ', sector: 'Textiles & Fashion' },
  { name: 'Uniform Supplier', nameMl: 'യൂണിഫോം', sector: 'Textiles & Fashion' },
  { name: 'Textile Wholesale', nameMl: 'തുണി മൊത്തം', sector: 'Textiles & Fashion' },
  { name: 'Embroidery & Stitching', nameMl: 'തുന്നൽ', sector: 'Textiles & Fashion' },
  { name: 'Handloom & Khadi', nameMl: 'കൈത്തറി', sector: 'Textiles & Fashion' },

  // Manufacturing & Industry
  { name: 'Coir Products', nameMl: 'കയർ', sector: 'Manufacturing & Industry' },
  { name: 'Cashew Processing', nameMl: 'കശുവണ്ടി', sector: 'Manufacturing & Industry' },
  { name: 'Printing & Packaging', nameMl: 'പ്രിന്റിംഗ് & പാക്കേജിംഗ്', sector: 'Manufacturing & Industry' },
  { name: 'Plastic Products', nameMl: 'പ്ലാസ്റ്റിക്', sector: 'Manufacturing & Industry' },
  { name: 'Wood & Timber', nameMl: 'തടി', sector: 'Manufacturing & Industry' },
  { name: 'Metal Fabrication', nameMl: 'മെറ്റൽ ഫേബ്രിക്കേഷൻ', sector: 'Manufacturing & Industry' },
  { name: 'Chemical & Cleaning Products', nameMl: 'ക്ലീനിംഗ് ഉൽപ്പന്നം', sector: 'Manufacturing & Industry' },

  // Entertainment & Events
  { name: 'Cinema / Theater', nameMl: 'സിനിമ', sector: 'Entertainment & Events' },
  { name: 'Event Management', nameMl: 'ഇവന്റ് മാനേജ്‌മെന്റ്', sector: 'Entertainment & Events' },
  { name: 'Wedding Planner', nameMl: 'വെഡ്ഡിംഗ് പ്ലാനർ', sector: 'Entertainment & Events' },
  { name: 'DJ & Sound System', nameMl: 'DJ & സൗണ്ട്', sector: 'Entertainment & Events' },
  { name: 'Decoration & Flowers', nameMl: 'ഡെക്കറേഷൻ', sector: 'Entertainment & Events' },
  { name: 'Fireworks', nameMl: 'ഫയർ വർക്ക്‌സ്', sector: 'Entertainment & Events' },
  { name: 'Band & Music for Events', nameMl: 'ബാൻഡ്', sector: 'Entertainment & Events' },
  { name: 'Tent & Furniture Rental', nameMl: 'ടെന്റ് & ഫർണിച്ചർ', sector: 'Entertainment & Events' },
  { name: 'Gaming Zone', nameMl: 'ഗെയിമിംഗ് സോൺ', sector: 'Entertainment & Events' },
  { name: 'Kids Party Organiser', nameMl: 'കിഡ്സ് പാർട്ടി', sector: 'Entertainment & Events' },
];

export const KERALA_DISTRICTS = [
  "Trivandrum", "Kollam", "Pathanamthitta", "Alappuzha", "Kottayam",
  "Idukki", "Ernakulam", "Kochi", "Thrissur", "Palakkad",
  "Malappuram", "Kozhikode", "Wayanad", "Kannur", "Kasaragod",
];

export const RATING_OPTIONS = ["4.5+ stars", "4.0+ stars", "3.5+ stars"];

export const WK = {
  paper: '#283618',
  ink: '#fefae0',
  sticky: '#dda15e',
  muted: '#a8a08a',
  tile: '#fefae0',
  hand: "var(--font-caveat), 'Caveat', cursive",
  mono: "var(--font-jetbrains), 'JetBrains Mono', monospace",
} as const;
