import 'package:fl_chart/fl_chart.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:share_plus/share_plus.dart';
import 'package:url_launcher/url_launcher.dart';
import '../../../core/constants/app_colors.dart';
import '../../../core/services/sales_summary_service.dart';
import '../../../providers/billing_provider.dart';
import '../../../providers/language_provider.dart';
import '../../../providers/orders_provider.dart';
import '../../../providers/shop_provider.dart';
import '../../../models/bill_model.dart';
import '../../../models/order_model.dart';
import '../../../shared/widgets/shimmer_list.dart';

class AnalyticsScreen extends ConsumerWidget {
  const AnalyticsScreen({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final translations = ref.watch(translationsProvider);
    String t(String key) => translations[key] ?? key;
    final shopAsync = ref.watch(activeShopIdProvider);

    return shopAsync.when(
      loading: () => const Scaffold(body: ShimmerList(itemCount: 3, itemHeight: 80)),
      error: (e, _) => Center(child: Text(e.toString())),
      data: (shopId) {
        if (shopId == null) return Center(child: Text(t('error_generic')));
        return _AnalyticsBody(shopId: shopId, t: t);
      },
    );
  }
}

class _AnalyticsBody extends ConsumerStatefulWidget {
  final String shopId;
  final String Function(String) t;
  const _AnalyticsBody({required this.shopId, required this.t});

  @override
  ConsumerState<_AnalyticsBody> createState() => _AnalyticsBodyState();
}

class _AnalyticsBodyState extends ConsumerState<_AnalyticsBody> {
  bool _sendingWhatsApp = false;

  // Cached analytics for share report
  double _revenue = 0;
  int _orderCount = 0;
  int _completedCount = 0;
  int _cancelledCount = 0;
  String _topProduct = '';
  String _currentPeriod = 'Today';

  void _updateAnalytics({
    required double revenue,
    required int orderCount,
    required int completedCount,
    required int cancelledCount,
    required String topProduct,
    required String period,
  }) {
    if (!mounted) return;
    setState(() {
      _revenue = revenue;
      _orderCount = orderCount;
      _completedCount = completedCount;
      _cancelledCount = cancelledCount;
      _topProduct = topProduct;
      _currentPeriod = period;
    });
  }

  void _shareReport() {
    final completionRate = _orderCount > 0
        ? (_completedCount / _orderCount * 100).toStringAsFixed(0)
        : '0';
    final text = '''📊 *Oratas Shop Report*
📅 $_currentPeriod
─────────────────
💰 Revenue: ₹${_revenue.toStringAsFixed(0)}
📦 Orders: $_orderCount
✅ Completed: $_completedCount
❌ Cancelled: $_cancelledCount
📈 Completion Rate: $completionRate%
─────────────────
${_topProduct.isNotEmpty ? '🏆 Top Product: $_topProduct\n─────────────────\n' : ''}Generated by Oratas''';
    Share.share(text);
  }

  Future<void> _sendSummaryToWhatsApp() async {
    setState(() => _sendingWhatsApp = true);
    try {
      final shopAsync = ref.read(shopStreamProvider(widget.shopId));
      final shop = shopAsync.valueOrNull;
      final shopName = shop?.shopName ?? 'My Shop';

      final summary =
          await SalesSummaryService.getTodaySummary(widget.shopId);
      final text =
          SalesSummaryService.formatSummaryText(summary, shopName);
      final encoded = Uri.encodeComponent(text);

      final phone =
          (shop?.ownerWhatsApp ?? '').replaceAll(RegExp(r'[^0-9]'), '');
      final url = phone.isNotEmpty
          ? 'https://wa.me/91$phone?text=$encoded'
          : 'https://wa.me/?text=$encoded';

      await launchUrl(Uri.parse(url), mode: LaunchMode.externalApplication);
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
              content: Text('Error: $e'), backgroundColor: Colors.red),
        );
      }
    } finally {
      if (mounted) setState(() => _sendingWhatsApp = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    final ordersAsync = ref.watch(ordersStreamProvider(widget.shopId));

    return Scaffold(
      backgroundColor: AppColors.background,
      appBar: AppBar(
        title: Text(widget.t('analytics_title')),
        backgroundColor: AppColors.primary,
        foregroundColor: Colors.white,
        actions: [
          IconButton(
            icon: const Icon(Icons.share_outlined),
            tooltip: 'Share Report',
            onPressed: _shareReport,
          ),
          Padding(
            padding: const EdgeInsets.only(right: 8),
            child: _sendingWhatsApp
                ? const Center(
                    child: SizedBox(
                      width: 22,
                      height: 22,
                      child: CircularProgressIndicator(
                          color: Colors.white, strokeWidth: 2),
                    ),
                  )
                : IconButton(
                    tooltip: 'Send to WhatsApp',
                    icon: const Icon(Icons.send),
                    onPressed: _sendSummaryToWhatsApp,
                  ),
          ),
        ],
      ),
      body: Column(
        children: [
          // Prominent WhatsApp summary button
          Padding(
            padding: const EdgeInsets.fromLTRB(16, 12, 16, 0),
            child: SizedBox(
              width: double.infinity,
              child: ElevatedButton.icon(
                icon: _sendingWhatsApp
                    ? const SizedBox(
                        width: 18,
                        height: 18,
                        child: CircularProgressIndicator(
                            color: Colors.white, strokeWidth: 2),
                      )
                    : const Icon(Icons.send, size: 18),
                label: const Text('Send Today\'s Summary to WhatsApp'),
                style: ElevatedButton.styleFrom(
                  backgroundColor: const Color(0xFF25D366),
                  foregroundColor: Colors.white,
                  padding: const EdgeInsets.symmetric(vertical: 12),
                  shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(10)),
                ),
                onPressed: _sendingWhatsApp ? null : _sendSummaryToWhatsApp,
              ),
            ),
          ),
          const SizedBox(height: 8),
          Expanded(
            child: _CombinedAnalytics(
              shopId: widget.shopId,
              ordersAsync: ordersAsync,
              t: widget.t,
              onAnalyticsReady: _updateAnalytics,
            ),
          ),
        ],
      ),
    );
  }
}

// Merges online orders + POS bills and renders _AnalyticsContent
class _CombinedAnalytics extends ConsumerWidget {
  final String shopId;
  final AsyncValue<List<OrderModel>> ordersAsync;
  final String Function(String) t;
  final void Function({
    required double revenue,
    required int orderCount,
    required int completedCount,
    required int cancelledCount,
    required String topProduct,
    required String period,
  }) onAnalyticsReady;

  const _CombinedAnalytics({
    required this.shopId,
    required this.ordersAsync,
    required this.t,
    required this.onAnalyticsReady,
  });

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final billsAsync = ref.watch(weeklyBillsProvider(shopId));

    return ordersAsync.when(
      loading: () => const ShimmerList(itemCount: 3, itemHeight: 80),
      error: (e, _) => Center(child: Text(e.toString())),
      data: (orders) => billsAsync.when(
        loading: () => _AnalyticsContent(
            orders: orders, bills: const [], t: t, onAnalyticsReady: onAnalyticsReady),
        error: (_, __) => _AnalyticsContent(
            orders: orders, bills: const [], t: t, onAnalyticsReady: onAnalyticsReady),
        data: (bills) => _AnalyticsContent(
            orders: orders, bills: bills, t: t, onAnalyticsReady: onAnalyticsReady),
      ),
    );
  }
}

class _AnalyticsContent extends StatefulWidget {
  final List<OrderModel> orders;
  final List<BillModel> bills;
  final String Function(String) t;
  final void Function({
    required double revenue,
    required int orderCount,
    required int completedCount,
    required int cancelledCount,
    required String topProduct,
    required String period,
  }) onAnalyticsReady;

  const _AnalyticsContent({
    required this.orders,
    required this.bills,
    required this.t,
    required this.onAnalyticsReady,
  });

  @override
  State<_AnalyticsContent> createState() => _AnalyticsContentState();
}

class _AnalyticsContentState extends State<_AnalyticsContent> {
  // 0=Today, 1=Week, 2=Month, 3=Custom
  int _periodIndex = 0;
  DateTimeRange? _customRange;

  Future<void> _pickRange() async {
    final now = DateTime.now();
    final picked = await showDateRangePicker(
      context: context,
      firstDate: now.subtract(const Duration(days: 365 * 2)),
      lastDate: now,
      initialDateRange: _customRange ??
          DateTimeRange(start: now.subtract(const Duration(days: 7)), end: now),
      builder: (ctx, child) => Theme(
        data: Theme.of(ctx).copyWith(
          colorScheme: const ColorScheme.light(primary: AppColors.primary),
        ),
        child: child!,
      ),
    );
    if (picked != null) setState(() { _customRange = picked; _periodIndex = 3; });
  }

  @override
  Widget build(BuildContext context) {
    final now = DateTime.now();
    final todayStart = DateTime(now.year, now.month, now.day);
    final weekStart  = todayStart.subtract(Duration(days: now.weekday - 1));
    final monthStart = DateTime(now.year, now.month, 1);

    DateTime rangeStart;
    DateTime rangeEnd = now;
    String periodLabel;

    switch (_periodIndex) {
      case 1: rangeStart = weekStart;  periodLabel = 'This Week';  break;
      case 2: rangeStart = monthStart; periodLabel = 'This Month'; break;
      case 3:
        rangeStart = _customRange?.start ?? todayStart;
        rangeEnd   = _customRange?.end   ?? now;
        final fmt  = (DateTime d) => '${d.day}/${d.month}';
        periodLabel = '${fmt(rangeStart)}–${fmt(rangeEnd)}';
        break;
      default: rangeStart = todayStart; periodLabel = 'Today'; break;
    }

    // Use the selected range to filter all data
    final filteredOrders = widget.orders
        .where((o) => o.createdAt.isAfter(rangeStart) && o.createdAt.isBefore(rangeEnd.add(const Duration(days: 1))))
        .toList();
    final filteredBills = widget.bills
        .where((b) => !b.isVoided && b.createdAt.isAfter(rangeStart) && b.createdAt.isBefore(rangeEnd.add(const Duration(days: 1))))
        .toList();

    // Keep the 3 fixed KPI cards (today/week/month) always visible for quick reference
    final todayOrders = widget.orders.where((o) => o.createdAt.isAfter(todayStart)).toList();
    final weekOrders  = widget.orders.where((o) => o.createdAt.isAfter(weekStart)).toList();
    final monthOrders = widget.orders.where((o) => o.createdAt.isAfter(monthStart)).toList();
    final todayBills  = widget.bills.where((b) => b.createdAt.isAfter(todayStart) && !b.isVoided).toList();
    final weekBills   = widget.bills.where((b) => b.createdAt.isAfter(weekStart) && !b.isVoided).toList();
    final monthBills  = widget.bills.where((b) => b.createdAt.isAfter(monthStart) && !b.isVoided).toList();

    final todayRevenue = todayOrders.fold(0.0, (s, o) => s + o.totalAmount)
        + todayBills.fold(0.0, (s, b) => s + b.finalAmount);
    final weekRevenue = weekOrders.fold(0.0, (s, o) => s + o.totalAmount)
        + weekBills.fold(0.0, (s, b) => s + b.finalAmount);
    final monthRevenue = monthOrders.fold(0.0, (s, o) => s + o.totalAmount)
        + monthBills.fold(0.0, (s, b) => s + b.finalAmount);

    final deliveredSelected =
        filteredOrders.where((o) => o.status == 'delivered').length;
    final completionRate =
        filteredOrders.isEmpty ? 0.0 : deliveredSelected / filteredOrders.length * 100;
    final filteredRevenue = filteredOrders.fold(0.0, (s, o) => s + o.totalAmount)
        + filteredBills.fold(0.0, (s, b) => s + b.finalAmount);

    // 7-day revenue sparkline — orders + bills combined
    final last7 = List.generate(7, (i) {
      final day = DateTime.now().subtract(Duration(days: 6 - i));
      final dayStart = DateTime(day.year, day.month, day.day);
      final dayEnd = dayStart.add(const Duration(days: 1));
      final orderRev = widget.orders
          .where((o) => o.createdAt.isAfter(dayStart) && o.createdAt.isBefore(dayEnd))
          .fold(0.0, (s, o) => s + o.totalAmount);
      final billRev = widget.bills
          .where((b) => !b.isVoided && b.createdAt.isAfter(dayStart) && b.createdAt.isBefore(dayEnd))
          .fold(0.0, (s, b) => s + b.finalAmount);
      return orderRev + billRev;
    });

    // Top 5 products in selected period
    final productCounts = <String, int>{};
    for (final o in filteredOrders) {
      for (final item in o.items) {
        productCounts[item.productName] =
            (productCounts[item.productName] ?? 0) + 1;
      }
    }
    for (final b in filteredBills) {
      for (final item in b.items) {
        productCounts[item.productName] =
            (productCounts[item.productName] ?? 0) + item.qty.toInt();
      }
    }
    final topProducts = productCounts.entries.toList()
      ..sort((a, b) => b.value.compareTo(a.value));
    final top5 = topProducts.take(5).toList();

    final maxProductCount = top5.isEmpty ? 1 : top5.first.value;

    // Peak hours — selected period
    final hourCounts = List<int>.filled(24, 0);
    for (final o in filteredOrders) hourCounts[o.createdAt.hour]++;
    for (final b in filteredBills)  hourCounts[b.createdAt.hour]++;

    // Notify parent for share report
    WidgetsBinding.instance.addPostFrameCallback((_) {
      widget.onAnalyticsReady(
        revenue: filteredRevenue,
        orderCount: filteredOrders.length + filteredBills.length,
        completedCount: deliveredSelected,
        cancelledCount: filteredOrders.where((o) => o.status == 'cancelled').length,
        topProduct: top5.isNotEmpty ? '${top5.first.key} (${top5.first.value} sold)' : '',
        period: periodLabel,
      );
    });

    return ListView(
      padding: const EdgeInsets.all(16),
      children: [
        // Period selector chips
        SingleChildScrollView(
          scrollDirection: Axis.horizontal,
          child: Row(children: [
            _PeriodChip(label: 'Today',      index: 0, selected: _periodIndex, onTap: (i) => setState(() { _periodIndex = i; })),
            const SizedBox(width: 8),
            _PeriodChip(label: 'This Week',  index: 1, selected: _periodIndex, onTap: (i) => setState(() { _periodIndex = i; })),
            const SizedBox(width: 8),
            _PeriodChip(label: 'This Month', index: 2, selected: _periodIndex, onTap: (i) => setState(() { _periodIndex = i; })),
            const SizedBox(width: 8),
            GestureDetector(
              onTap: _pickRange,
              child: Container(
                padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 7),
                decoration: BoxDecoration(
                  color: _periodIndex == 3 ? AppColors.primary : Colors.transparent,
                  borderRadius: BorderRadius.circular(20),
                  border: Border.all(color: _periodIndex == 3 ? AppColors.primary : Colors.grey.shade400),
                ),
                child: Row(mainAxisSize: MainAxisSize.min, children: [
                  Icon(Icons.date_range, size: 14,
                      color: _periodIndex == 3 ? Colors.white : AppColors.textSecondary),
                  const SizedBox(width: 4),
                  Text(
                    _periodIndex == 3 ? periodLabel : 'Custom',
                    style: TextStyle(
                      fontSize: 13,
                      color: _periodIndex == 3 ? Colors.white : AppColors.textSecondary,
                      fontWeight: _periodIndex == 3 ? FontWeight.w600 : FontWeight.normal,
                    ),
                  ),
                ]),
              ),
            ),
          ]),
        ),
        const SizedBox(height: 16),

        // Selected period summary card
        Container(
          padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 14),
          decoration: BoxDecoration(
            color: AppColors.primary,
            borderRadius: BorderRadius.circular(14),
          ),
          child: Row(
            mainAxisAlignment: MainAxisAlignment.spaceAround,
            children: [
              _SummaryChip('₹${filteredRevenue.toInt()}', 'Revenue'),
              _SummaryChip('${filteredOrders.length + filteredBills.length}', 'Sales'),
              _SummaryChip('${completionRate.toStringAsFixed(0)}%', 'Completed'),
            ],
          ),
        ),
        const SizedBox(height: 16),

        // Hero KPI tiles
        _SectionTitle(widget.t('analytics_overview')),
        const SizedBox(height: 8),
        Row(children: [
          _KpiCard(
            label: widget.t('analytics_today'),
            value: '₹${todayRevenue.toInt()}',
            subValue: '${todayOrders.length + todayBills.length} sales',
            color: AppColors.primary,
          ),
          const SizedBox(width: 8),
          _KpiCard(
            label: widget.t('analytics_week'),
            value: '₹${weekRevenue.toInt()}',
            subValue: '${weekOrders.length + weekBills.length} sales',
            color: const Color(0xFF1976D2),
          ),
          const SizedBox(width: 8),
          _KpiCard(
            label: widget.t('analytics_month'),
            value: '₹${monthRevenue.toInt()}',
            subValue: '${monthOrders.length + monthBills.length} sales',
            color: AppColors.success,
          ),
        ]),
        const SizedBox(height: 12),
        _CompletionCard(rate: completionRate, t: widget.t),
        const SizedBox(height: 12),
        _SparklineChart(values: last7),
        const SizedBox(height: 16),

        // Top products
        _SectionTitle(widget.t('analytics_top_products')),
        const SizedBox(height: 8),
        if (top5.isEmpty)
          _EmptyCard(widget.t('analytics_no_data'))
        else
          ...top5.asMap().entries.map((e) => _ProductRankTile(
                rank: e.key + 1,
                name: e.value.key,
                count: e.value.value,
                maxCount: maxProductCount,
              )),
        const SizedBox(height: 16),

        // Peak hours chart
        _SectionTitle(widget.t('analytics_peak_hours')),
        const SizedBox(height: 8),
        _PeakHoursChart(hourCounts: hourCounts),
        const SizedBox(height: 20),
      ],
    );
  }
}

// ─── Period chip ────────────────────────────────────────────────────────────

class _PeriodChip extends StatelessWidget {
  final String label;
  final int index;
  final int selected;
  final ValueChanged<int> onTap;
  const _PeriodChip({required this.label, required this.index, required this.selected, required this.onTap});

  @override
  Widget build(BuildContext context) {
    final isSelected = index == selected;
    return GestureDetector(
      onTap: () => onTap(index),
      child: Container(
        padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 7),
        decoration: BoxDecoration(
          color: isSelected ? AppColors.primary : Colors.transparent,
          borderRadius: BorderRadius.circular(20),
          border: Border.all(color: isSelected ? AppColors.primary : Colors.grey.shade400),
        ),
        child: Text(
          label,
          style: TextStyle(
            fontSize: 13,
            color: isSelected ? Colors.white : AppColors.textSecondary,
            fontWeight: isSelected ? FontWeight.w600 : FontWeight.normal,
          ),
        ),
      ),
    );
  }
}

class _SummaryChip extends StatelessWidget {
  final String value;
  final String label;
  const _SummaryChip(this.value, this.label);

  @override
  Widget build(BuildContext context) => Column(
    children: [
      Text(value, style: const TextStyle(color: Colors.white, fontSize: 20, fontWeight: FontWeight.w800)),
      const SizedBox(height: 2),
      Text(label, style: const TextStyle(color: Colors.white70, fontSize: 11)),
    ],
  );
}

// ─── KPI Card (replaces _StatCard) ──────────────────────────────────────────

class _KpiCard extends StatelessWidget {
  final String label;
  final String value;
  final String subValue;
  final Color color;
  const _KpiCard(
      {required this.label,
      required this.value,
      required this.subValue,
      required this.color});

  @override
  Widget build(BuildContext context) {
    return Expanded(
      child: Container(
        padding: const EdgeInsets.all(16),
        decoration: BoxDecoration(
          color: Colors.white,
          borderRadius: BorderRadius.circular(14),
          border: Border.all(color: Colors.grey.shade200),
          boxShadow: [
            BoxShadow(
                color: Colors.black.withValues(alpha: 0.04),
                blurRadius: 6,
                offset: const Offset(0, 2))
          ],
        ),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(label,
                style: const TextStyle(
                    fontSize: 11,
                    color: AppColors.textSecondary,
                    fontWeight: FontWeight.w500)),
            const SizedBox(height: 8),
            Text(value,
                style: TextStyle(
                    fontSize: 22,
                    fontWeight: FontWeight.w800,
                    color: color)),
            const SizedBox(height: 2),
            Text(subValue,
                style: const TextStyle(
                    fontSize: 11, color: AppColors.textSecondary)),
          ],
        ),
      ),
    );
  }
}

// ─── 7-Day Revenue Sparkline ─────────────────────────────────────────────────

class _SparklineChart extends StatelessWidget {
  final List<double> values;
  const _SparklineChart({required this.values});

  @override
  Widget build(BuildContext context) {
    final maxY = values.reduce((a, b) => a > b ? a : b);
    return Container(
      height: 120,
      padding: const EdgeInsets.all(12),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(14),
        border: Border.all(color: Colors.grey.shade200),
        boxShadow: [
          BoxShadow(
              color: Colors.black.withValues(alpha: 0.04),
              blurRadius: 6,
              offset: const Offset(0, 2))
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const Text('7-Day Revenue',
              style: TextStyle(
                  fontSize: 12,
                  fontWeight: FontWeight.w600,
                  color: AppColors.textSecondary)),
          const SizedBox(height: 8),
          Expanded(
            child: LineChart(
              LineChartData(
                gridData: const FlGridData(show: false),
                borderData: FlBorderData(show: false),
                titlesData: const FlTitlesData(show: false),
                lineBarsData: [
                  LineChartBarData(
                    spots: values
                        .asMap()
                        .entries
                        .map((e) => FlSpot(e.key.toDouble(), e.value))
                        .toList(),
                    isCurved: true,
                    color: AppColors.primary,
                    barWidth: 2.5,
                    dotData: const FlDotData(show: false),
                    belowBarData: BarAreaData(
                      show: true,
                      color: AppColors.primary.withValues(alpha: 0.08),
                    ),
                  ),
                ],
                minY: 0,
                maxY: maxY < 1 ? 1 : maxY * 1.2,
              ),
            ),
          ),
        ],
      ),
    );
  }
}

// ─── Completion Card (improved with circular progress) ───────────────────────

class _CompletionCard extends StatelessWidget {
  final double rate;
  final String Function(String) t;
  const _CompletionCard({required this.rate, required this.t});

  @override
  Widget build(BuildContext context) {
    final progress = (rate / 100).clamp(0.0, 1.0);
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 14),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(14),
        border: Border.all(color: Colors.grey.shade200),
        boxShadow: [
          BoxShadow(
              color: Colors.black.withValues(alpha: 0.04),
              blurRadius: 6,
              offset: const Offset(0, 2))
        ],
      ),
      child: Row(children: [
        // Circular progress indicator
        SizedBox(
          width: 52,
          height: 52,
          child: Stack(
            fit: StackFit.expand,
            children: [
              CircularProgressIndicator(
                value: progress,
                strokeWidth: 5,
                backgroundColor: Colors.grey.shade200,
                valueColor:
                    const AlwaysStoppedAnimation<Color>(AppColors.success),
              ),
              Center(
                child: Text(
                  '${rate.toStringAsFixed(0)}%',
                  style: const TextStyle(
                      fontSize: 11,
                      fontWeight: FontWeight.bold,
                      color: AppColors.success),
                ),
              ),
            ],
          ),
        ),
        const SizedBox(width: 16),
        Expanded(
          child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(t('analytics_completion'),
                    style: const TextStyle(
                        color: AppColors.textSecondary, fontSize: 12)),
                const SizedBox(height: 4),
                Text('${rate.toStringAsFixed(0)}%',
                    style: const TextStyle(
                        fontSize: 28,
                        fontWeight: FontWeight.w800,
                        color: AppColors.success)),
                const SizedBox(height: 2),
                // Linear bar under the large number
                ClipRRect(
                  borderRadius: BorderRadius.circular(4),
                  child: LinearProgressIndicator(
                    value: progress,
                    minHeight: 6,
                    backgroundColor: Colors.grey.shade200,
                    valueColor: const AlwaysStoppedAnimation<Color>(
                        AppColors.success),
                  ),
                ),
              ]),
        ),
        const SizedBox(width: 12),
        Text(t('analytics_this_month'),
            style: const TextStyle(
                color: AppColors.textSecondary, fontSize: 11)),
      ]),
    );
  }
}

// ─── Product Rank Tile (with proportional bar) ───────────────────────────────

class _ProductRankTile extends StatelessWidget {
  final int rank;
  final String name;
  final int count;
  final int maxCount;
  const _ProductRankTile(
      {required this.rank,
      required this.name,
      required this.count,
      required this.maxCount});

  @override
  Widget build(BuildContext context) {
    final fraction = maxCount > 0 ? count / maxCount : 0.0;
    return Container(
      margin: const EdgeInsets.only(bottom: 8),
      padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 12),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(10),
        border: Border.all(color: Colors.grey.shade200),
      ),
      child: Column(
        children: [
          Row(children: [
            // Rank badge
            Container(
              width: 26,
              height: 26,
              decoration: BoxDecoration(
                color: rank == 1
                    ? Colors.amber
                    : AppColors.primary.withValues(alpha: 0.1),
                shape: BoxShape.circle,
              ),
              child: Center(
                child: Text('$rank',
                    style: TextStyle(
                        fontSize: 11,
                        fontWeight: FontWeight.bold,
                        color:
                            rank == 1 ? Colors.white : AppColors.primary)),
              ),
            ),
            const SizedBox(width: 10),
            Expanded(
                child: Text(name,
                    style: const TextStyle(fontWeight: FontWeight.w500))),
            Text('$count orders',
                style: const TextStyle(
                    color: AppColors.textSecondary, fontSize: 12)),
          ]),
          const SizedBox(height: 8),
          // Proportional popularity bar
          ClipRRect(
            borderRadius: BorderRadius.circular(4),
            child: LinearProgressIndicator(
              value: fraction,
              minHeight: 5,
              backgroundColor: Colors.grey.shade100,
              valueColor: AlwaysStoppedAnimation<Color>(
                rank == 1 ? Colors.amber.shade600 : AppColors.primaryLight,
              ),
            ),
          ),
        ],
      ),
    );
  }
}

// ─── Shared helpers ───────────────────────────────────────────────────────────

class _SectionTitle extends StatelessWidget {
  final String text;
  const _SectionTitle(this.text);
  @override
  Widget build(BuildContext context) => Text(text,
      style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 15));
}

class _EmptyCard extends StatelessWidget {
  final String message;
  const _EmptyCard(this.message);
  @override
  Widget build(BuildContext context) => Container(
        padding: const EdgeInsets.all(20),
        decoration: BoxDecoration(
          color: Colors.white,
          borderRadius: BorderRadius.circular(10),
          border: Border.all(color: Colors.grey.shade200),
        ),
        child: Center(
            child: Text(message,
                style:
                    const TextStyle(color: AppColors.textSecondary))),
      );
}

// ─── Peak Hours Bar Chart ─────────────────────────────────────────────────────

class _PeakHoursChart extends StatelessWidget {
  final List<int> hourCounts;
  const _PeakHoursChart({required this.hourCounts});

  @override
  Widget build(BuildContext context) {
    final maxVal =
        hourCounts.reduce((a, b) => a > b ? a : b).toDouble();

    return Container(
      height: 180,
      padding: const EdgeInsets.fromLTRB(8, 12, 12, 8),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(10),
        border: Border.all(color: Colors.grey.shade200),
      ),
      child: BarChart(
        BarChartData(
          maxY: maxVal < 1 ? 1 : maxVal + 1,
          gridData: const FlGridData(show: false),
          borderData: FlBorderData(show: false),
          titlesData: FlTitlesData(
            leftTitles:
                const AxisTitles(sideTitles: SideTitles(showTitles: false)),
            topTitles:
                const AxisTitles(sideTitles: SideTitles(showTitles: false)),
            rightTitles:
                const AxisTitles(sideTitles: SideTitles(showTitles: false)),
            bottomTitles: AxisTitles(
              sideTitles: SideTitles(
                showTitles: true,
                getTitlesWidget: (val, _) {
                  final h = val.toInt();
                  if (h % 6 != 0) return const SizedBox.shrink();
                  final label = h == 0
                      ? '12a'
                      : h < 12
                          ? '${h}a'
                          : h == 12
                              ? '12p'
                              : '${h - 12}p';
                  return Text(label,
                      style: const TextStyle(
                          fontSize: 10, color: AppColors.textSecondary));
                },
              ),
            ),
          ),
          barGroups: List.generate(
              24,
              (h) => BarChartGroupData(
                    x: h,
                    barRods: [
                      BarChartRodData(
                        toY: hourCounts[h].toDouble(),
                        color: AppColors.primary,
                        width: 8,
                        borderRadius: BorderRadius.circular(3),
                      ),
                    ],
                  )),
        ),
      ),
    );
  }
}
